# Generated by Django 3.0.5 on 2020-07-16 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='token',
        ),
        migrations.CreateModel(
            name='RelationshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('blocked', models.BooleanField(default=False, verbose_name='Indicates if the relationship was blocked')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='date when was generated')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('addressed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_request_addressed', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_request_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'relationshiprequest',
            },
        ),
    ]
