# Generated by Django 3.0.5 on 2020-07-18 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200716_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='relationshiprequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='date when was generated'),
        ),
        migrations.AlterField(
            model_name='relationshiprequest',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
