# Generated by Django 3.0.5 on 2020-08-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200718_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default="Querido usuario", help_text='Complete real name of the user', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username generated by the system', max_length=50, unique=True),
        ),
    ]
