# Generated by Django 3.0.5 on 2020-09-02 12:46

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200825_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='verification',
            name='state',
            field=models.CharField(choices=[(users.models.Verification.States['NONE'], 'None'), (users.models.Verification.States['INPROGRESS'], 'InProgress'), (users.models.Verification.States['STOPPED'], 'Stopped'), (users.models.Verification.States['LOCKED'], 'Locked'), (users.models.Verification.States['SUCCESS'], 'Success')], default='None', max_length=15),
        ),
    ]
