# Generated by Django 3.0.5 on 2020-09-07 20:49

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200906_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
    ]
