# Generated by Django 3.0.5 on 2021-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='description',
            field=models.CharField(blank=True, help_text='\n            Description of the supplier that is going to be displayed \n            in the profile. Is indepent from the company desciption. \n\n            But by default this value is going to be loaded with the description of the company', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='display_name',
            field=models.CharField(help_text="\n            Name that is going to be displayed in the profile. This isn't \n            the real name of the company, is a completely election of the profile owner.\n\n            By default the real company name is going to be selected.", max_length=60),
        ),
    ]
