# Generated by Django 3.0.5 on 2021-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20210108_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, help_text='description for add the principal characteristics of the product.', max_length=500, null=True),
        ),
    ]
