# Generated by Django 3.0.5 on 2021-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_auto_20210129_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='description for add the principal characteristics of the product.', max_length=500, null=True),
        ),
    ]
