# Generated by Django 3.0.5 on 2021-01-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20210129_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='description for add the principal characteristics of the product.', null=True),
        ),
    ]
