AWS_UPLOAD_BUCKET = "business-network-profile-files"

AWS_UPLOAD_USERNAME = "business-network-api-core-user"

AWS_UPLOAD_GROUP = "business-network-multimedia-clients"

AWS_UPLOAD_REGION = "us-west-1"

AWS_UPLOAD_ACCESS_KEY_ID = "AKIA4BR2HNWAP3TUWE6C"

AWS_UPLOAD_SECRET_KEY = "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"

AWS_ACCESS_KEY_ID = "AKIA4BR2HNWAP3TUWE6C"

AWS_SECRET_ACCESS_KEY_ID = "MtzOoUURFFr6uZHG9aPtiA3P6rwS6sjCOZQvSIgr"

AWS_DEFAULT_ACL = None