# Generated by Django 3.0.5 on 2021-01-17 12:57

from django.db import migrations, models
import django.utils.timezone
import multimedia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Is the name as the file is saved in the storage system', max_length=60)),
                ('relative_path', models.TextField(blank=True, help_text='path inside the storage - Not take in account domain (Ej: https://...)', null=True)),
                ('absolute_path', models.TextField(blank=True, help_text='the complete path where is in the internet')),
                ('size', models.CharField(help_text='Size of the file in bytes', max_length=7)),
                ('type', models.CharField(blank=True, choices=[(multimedia.models.File.Types['PDF'], (('PDF', 'application/pdf'),))], help_text='Format, Ej: application/pdf, etc...', max_length=17)),
                ('uploaded', models.BooleanField(default=False, help_text='stores if the file could be uploaded')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='date when was created')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='the name of the image as is located', max_length=120)),
                ('relative_path', models.TextField(blank=True, help_text='path inside the storage - Not take in account domain (Ej: https://...)')),
                ('absolute_path', models.TextField(blank=True, help_text='the complete path where is in the internet')),
                ('width', models.CharField(max_length=8)),
                ('height', models.CharField(max_length=8)),
                ('size', models.CharField(help_text='Size of the image in bytes', max_length=7)),
                ('type', models.CharField(choices=[(multimedia.models.Image.Types['JPEG'], (('JPEG', 'image/JPEG'),)), (multimedia.models.Image.Types['JPG'], (('JPG', 'image/JPG'),)), (multimedia.models.Image.Types['PNG'], (('PNG', 'image/PNG'),))], max_length=17)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='date when was created')),
                ('uploaded', models.BooleanField(default=False, help_text='stores if the file could be uploaded')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='the name of the video as is located', max_length=120)),
                ('relative_path', models.TextField(blank=True, help_text='path inside the storage - Not take in account domain (Ej: https://...)')),
                ('absolute_path', models.TextField(blank=True, help_text='the complete path where is in the internet')),
                ('length', models.FloatField(help_text='Duration of the video in seconds', max_length=5)),
                ('size', models.CharField(help_text='Size of the video in bytes', max_length=9)),
                ('type', models.CharField(choices=[(multimedia.models.Video.Types['MP4'], (('MP4', 'video/mp4'),)), (multimedia.models.Video.Types['WEBM'], (('WEBM', 'video/webm'),)), (multimedia.models.Video.Types['OGG'], (('OGG', 'video/ogg'),))], max_length=17)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='date when was created')),
                ('uploaded', models.BooleanField(default=False, help_text='stores if the file could be uploaded')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
