# Generated by Django 3.0.5 on 2021-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.CharField(help_text='Size of the image in bytes', max_length=8),
        ),
    ]
