# Generated by Django 3.0.5 on 2021-01-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multimedia', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'showcasesection',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tariff_heading', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('supplier_name', models.CharField(max_length=60)),
                ('supplier_acountname', models.CharField(max_length=50)),
                ('principal_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='multimedia.Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.Product')),
                ('showcase_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.ShowcaseSection')),
            ],
            options={
                'db_table': 'showcaseproduct',
            },
        ),
    ]
