# Generated by Django 3.0.5 on 2020-11-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tariff_heading', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('company_name', models.CharField(max_length=60)),
                ('company_username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'showcaseproduct',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'showcasesection',
            },
        ),
    ]
