# Generated by Django 3.0.5 on 2020-10-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0009_auto_20201017_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('slug_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ShowcaseProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tariff_heading', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('image_path', models.TextField(blank=True, help_text='the complete path where is in the internet', null=True)),
                ('company_name', models.CharField(max_length=60)),
                ('company_username', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Product')),
                ('showcase_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.ShowcaseSection')),
            ],
        ),
    ]
