# Generated by Django 3.0.5 on 2021-02-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseproduct',
            name='maximum_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper limit of the price. If this value exists means that\n            there is a range of prices in which the companies can negotiate.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='showcaseproduct',
            name='measurement_unit',
            field=models.CharField(blank=True, help_text='Type of unit that is used to measure and offer the product.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='showcaseproduct',
            name='minimum_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lower limit of the price. If there is no \n            maximum_price there is only going to be one absolute price.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='showcaseproduct',
            name='minimum_purchase',
            field=models.CharField(blank=True, help_text='minimum amount for which the product owner is willing to sell the product.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='showcaseproduct',
            name='description',
            field=models.TextField(blank=True, help_text='description for add the principal characteristics of the product.', null=True),
        ),
        migrations.AlterField(
            model_name='showcaseproduct',
            name='name',
            field=models.CharField(help_text='name or title as is going to be displayed the product', max_length=50),
        ),
        migrations.AlterField(
            model_name='showcaseproduct',
            name='principal_image',
            field=models.ForeignKey(help_text='Image that appears in the cover of the product. \n            Is the first visible image everywhere.', null=True, on_delete=django.db.models.deletion.PROTECT, to='multimedia.Image'),
        ),
        migrations.AlterField(
            model_name='showcaseproduct',
            name='supplier_accountname',
            field=models.CharField(help_text='accountname of the supplier that is selling the product', max_length=50),
        ),
        migrations.AlterField(
            model_name='showcaseproduct',
            name='supplier_name',
            field=models.CharField(help_text='name of the supplier that is selling the product', max_length=60),
        ),
        migrations.AlterField(
            model_name='showcaseproduct',
            name='tariff_heading',
            field=models.CharField(blank=True, help_text='Value that is used in foreign trade to identify uniquely a product.', max_length=20, null=True),
        ),
    ]
