# Generated by Django 3.0.5 on 2020-10-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='showcaseproduct',
            table='showcaseproduct',
        ),
        migrations.AlterModelTable(
            name='showcasesection',
            table='showcasesection',
        ),
    ]
