# Generated by Django 3.0.5 on 2020-11-11 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('multimedia', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseproduct',
            name='principal_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='multimedia.Image'),
        ),
        migrations.AddField(
            model_name='showcaseproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Product'),
        ),
        migrations.AddField(
            model_name='showcaseproduct',
            name='showcase_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.ShowcaseSection'),
        ),
    ]
