# Generated by Django 3.0.5 on 2020-10-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20201018_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showcaseproduct',
            old_name='showcase_category',
            new_name='showcase_section',
        ),
        migrations.RemoveField(
            model_name='showcasesection',
            name='slug_name',
        ),
    ]
