# Generated by Django 3.0.5 on 2021-01-08 00:00

import companies.constants
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text="Name that is going to be displayed in the profile. This isn't \n            the real name of the company, is a completely election of the profile owner.\n\n            By default the real company name is going to be selected.", max_length=60)),
                ('description', models.CharField(blank=True, help_text='Description of the supplier that is going to be displayed \n            in the profile. Is indepent from the company desciption. But by default \n            this value is going to be loaded with the description of the company', max_length=155, null=True)),
                ('contact_area_code', models.CharField(blank=True, help_text='area code of the contact channel of a buyer profile', max_length=5, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='phone number of the contact channel of a buyer profile', max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='email of the contact channel of a buyer profile', max_length=254, null=True)),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='date when the profile was activated')),
                ('visibility', models.CharField(choices=[(companies.constants.VisibilityState['PRIVATE'], 'PRIVATE'), (companies.constants.VisibilityState['OPEN'], 'OPEN'), (companies.constants.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (companies.constants.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20)),
            ],
            options={
                'db_table': 'buyer_profile',
            },
        ),
    ]
