# Generated by Django 3.0.5 on 2020-04-24 23:09

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('industry', models.CharField(blank=True, max_length=60, null=True)),
                ('web_url', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('hired', models.CharField(max_length=1)),
                ('celphone', models.CharField(max_length=14, unique=True)),
                ('charge', models.CharField(max_length=45)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Socialnetwork',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('privacy', models.CharField(blank=True, max_length=9, null=True)),
                ('profile_image_url', models.CharField(blank=True, max_length=150, null=True)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
            ],
            options={
                'db_table': 'socialnetwork',
            },
        ),
        migrations.CreateModel(
            name='Companysocialnetwork',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='companies.Company')),
            ],
            options={
                'db_table': 'companysocialnetwork',
            },
        ),
        migrations.CreateModel(
            name='Employeesocialnetwork',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='companies.Employee')),
            ],
            options={
                'db_table': 'employeesocialnetwork',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.Media')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.Media')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('zip', models.CharField(blank=True, max_length=45, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
            ],
            options={
                'db_table': 'interest',
            },
        ),
        migrations.CreateModel(
            name='Importantevents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_url', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('company', models.ForeignKey(db_column='Company_id', on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.Media')),
            ],
            options={
                'db_table': 'importantevents',
            },
        ),
        migrations.CreateModel(
            name='Dnaelement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.Media')),
            ],
            options={
                'db_table': 'dnaelement',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('ext_phone', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
