# Generated by Django 3.0.5 on 2021-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='number_of_logins_in_buyer_profile',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companymember',
            name='number_of_logins_in_supplier_profile',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_buyer',
            field=models.BooleanField(default=False, help_text='Designates if the company has a buyer profile and its capabilites', verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='Designates if the company has a supplier profile and its capabilites', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set to true when the company existence and legality is verified', verbose_name='verified'),
        ),
    ]
