# Generated by Django 3.0.5 on 2020-11-11 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multimedia', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ManyToManyField(to='multimedia.Image'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multimedia.Image'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Product'),
        ),
        migrations.AddField(
            model_name='productcertificate',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Certificate'),
        ),
        migrations.AddField(
            model_name='productcertificate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='certificates',
            field=models.ManyToManyField(through='companies.ProductCertificate', to='companies.Certificate'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(through='companies.ProductImage', to='multimedia.Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Currency'),
        ),
        migrations.AddField(
            model_name='interest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='importantevent',
            name='company',
            field=models.ForeignKey(db_column='Company_id', on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='importantevent',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Image'),
        ),
        migrations.AddField(
            model_name='employeesocialnetwork',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Employee'),
        ),
        migrations.AddField(
            model_name='employeesocialnetwork',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Socialnetwork'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='dnaelement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='dnaelement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Image'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='companysocialnetwork',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='companysocialnetwork',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Socialnetwork'),
        ),
        migrations.AddField(
            model_name='companysalelocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='headquarters_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Image'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Certificate'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Image'),
        ),
    ]
