# Generated by Django 3.0.5 on 2020-04-24 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Verification'),
        ),
        migrations.AddField(
            model_name='employeesocialnetwork',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Socialnetwork'),
        ),
        migrations.AddField(
            model_name='companysocialnetwork',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Socialnetwork'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesocialnetwork',
            unique_together={('employee', 'social_network')},
        ),
        migrations.AlterUniqueTogether(
            name='companysocialnetwork',
            unique_together={('company', 'social_network')},
        ),
    ]
