# Generated by Django 3.0.5 on 2020-09-09 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200907_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='maximum_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_price',
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maximum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='companies.Currency')),
            ],
            options={
                'db_table': 'productpricing',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='pricing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.ProductPricing'),
        ),
    ]
