# Generated by Django 3.0.5 on 2020-11-11 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_auto_20201111_1756'),
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Logo that represents the certificate authority', null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Image'),
        ),
        migrations.AlterUniqueTogether(
            name='unregisteredrelationship',
            unique_together={('requester', 'unregistered')},
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='productcertificate',
            unique_together={('product', 'certificate')},
        ),
        migrations.AlterUniqueTogether(
            name='employeesocialnetwork',
            unique_together={('employee', 'social_network')},
        ),
        migrations.AlterUniqueTogether(
            name='companysocialnetwork',
            unique_together={('company', 'social_network')},
        ),
        migrations.AlterUniqueTogether(
            name='companycertificate',
            unique_together={('company', 'certificate')},
        ),
    ]
