# Generated by Django 3.0.5 on 2020-11-17 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20201111_1756'),
        ('companies', '0003_auto_20201111_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ext_phone',
            new_name='area_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='companylocation',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='company',
            name='principal_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_principal_contact', to='companies.Contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='principal_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_principal_location', to='companies.CompanyLocation'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='principal_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_principal_image', to='multimedia.Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_images',
            field=models.ManyToManyField(related_name='product_secondary_images', through='companies.ProductImage', to='multimedia.Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_purchase',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
