# Generated by Django 3.0.5 on 2020-06-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_document_verification'),
        ('companies', '0003_auto_20200624_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredCompany',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('industry', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Importantevents',
            new_name='ImportantEvent',
        ),
    ]
