# Generated by Django 3.0.5 on 2020-05-13 23:22

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20200512_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[(companies.models.Media.Types['IMAGE'], 'image'), (companies.models.Media.Types['VIDEO'], 'video')], max_length=10),
        ),
    ]
