# Generated by Django 3.0.5 on 2020-06-28 21:54

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20200628_1235'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unregisteredcompany',
            table='unregisteredcompany',
        ),
        migrations.CreateModel(
            name='UnregisteredRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('requester', models.ForeignKey(help_text='Is the company that request the relationship.It exist in the platform and is registered', on_delete=django.db.models.deletion.PROTECT, related_name='relation_requester', to='companies.Company')),
                ('unregistered', models.ForeignKey(help_text='Is the company that is not official registered in the platform.It was created by another user that could not find its partners registeredbut wants to show it in its relationships, or was created by an admin', on_delete=django.db.models.deletion.PROTECT, related_name='relation_unregistered', to='companies.UnregisteredCompany')),
            ],
            options={
                'db_table': 'unregisteredrelationship',
                'unique_together': {('requester', 'unregistered')},
            },
        ),
    ]
