# Generated by Django 3.0.5 on 2020-09-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200909_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='country',
            new_name='region',
        ),
    ]
