# Generated by Django 3.0.5 on 2020-09-09 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200909_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricing',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Currency'),
        ),
    ]
