# Generated by Django 3.0.5 on 2020-07-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200628_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
