# Generated by Django 3.0.5 on 2020-08-31 22:23

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_document_verification'),
        ('companies', '0006_auto_20200706_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='multimedia.Media')),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default=users.models.VisibilityState['OPEN'], max_length=20)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Certificate')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
            ],
            options={
                'db_table': 'companycertificate',
                'unique_together': {('company', 'certificate')},
            },
        ),
    ]
