# Generated by Django 3.0.5 on 2020-09-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20200909_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysocialnetwork',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesocialnetwork',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unregisteredcompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='unregisteredcompany',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='unregisteredcompany',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
