# Generated by Django 3.0.5 on 2020-10-18 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20200911_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maximum_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, default=0.99, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='companies.Currency'),
            preserve_default=False,
        ),
    ]
