# Generated by Django 3.0.5 on 2020-09-02 12:46

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_document_verification'),
        ('companies', '0007_auto_20200831_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='maximum_price',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='url',
            new_name='profile_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='media',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_purchase',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tariff_heading',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Media'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Media'),
        ),
        migrations.AlterField(
            model_name='company',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='companycertificate',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysocialnetwork',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Socialnetwork'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='dnaelement',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Media'),
        ),
        migrations.AlterField(
            model_name='dnaelement',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeesocialnetwork',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Socialnetwork'),
        ),
        migrations.AlterField(
            model_name='importantevent',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Media'),
        ),
        migrations.AlterField(
            model_name='importantevent',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='interest',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Media'),
        ),
        migrations.AlterField(
            model_name='location',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Media'),
        ),
        migrations.AlterField(
            model_name='service',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='unregisteredrelationship',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'Private'), (users.models.VisibilityState['OPEN'], 'Open'), (users.models.VisibilityState['PERSONALIZED'], 'Personalized'), (users.models.VisibilityState['DELETED'], 'Deleted')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.Media')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='companies.Product')),
            ],
            options={
                'db_table': 'productmedia',
                'unique_together': {('product', 'media')},
            },
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Certificate')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='companies.Product')),
            ],
            options={
                'db_table': 'productcertificate',
                'unique_together': {('product', 'certificate')},
            },
        ),
    ]
