# Generated by Django 3.0.5 on 2020-10-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20201017_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pricing',
        ),
        migrations.DeleteModel(
            name='ProductPricing',
        ),
    ]
