# Generated by Django 3.0.5 on 2020-11-10 15:32

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_auto_20200906_1857'),
        ('companies', '0009_auto_20201017_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('zip', models.CharField(blank=True, max_length=45, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
                ('headquarters_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Image')),
            ],
            options={
                'db_table': 'companylocation',
            },
        ),
        migrations.CreateModel(
            name='CompanySaleLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('visibility', models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company')),
            ],
            options={
                'db_table': 'companysalelocation',
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
