# Generated by Django 3.0.5 on 2020-09-07 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_auto_20200906_1857'),
        ('companies', '0010_auto_20200906_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multimedia.Image'),
        ),
    ]
