# Generated by Django 3.0.5 on 2020-09-07 20:49

from django.db import migrations, models
import users.models
import companies.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20200906_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='companycertificate',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='dnaelement',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='importantevent',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='interest',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='unregisteredrelationship',
            name='visibility',
            field=models.CharField(choices=[(users.models.VisibilityState['PRIVATE'], 'PRIVATE'), (users.models.VisibilityState['OPEN'], 'OPEN'), (users.models.VisibilityState['PERSONALIZED'], 'PERSONALIZED'), (users.models.VisibilityState['DELETED'], 'DELETED')], default='OPEN', max_length=20),
        ),
    ]
